FROM openjdk:17-alpine
RUN mkdir /output
RUN cp /home/runner/work/PackageService/PackageService/target/packageservice-1.0-SNAPSHOT.jar /output
ENTRYPOINT ["java","-jar","/output/packageservice-1.0-SNAPSHOT.jar"]